
trigger:
- main

variables:
  location: 'East US'
  acc: 'Arroyo_Challenge-Test_Maximiliano'
  vm_bicep: vm.bicep
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(acc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      if [ $(az group exists --name ADO) = false ]; then
        az group create --name ADO --location '$(location)'
      fi

      kvExists=$(az keyvault show --name MaxiPruebaTecKeyVault --resource-group ADO --query 'name' -o tsv)
      echo $(kvExists)
      if [ -z "$kvExists" ]; then
        echo "creating kv"
        az keyvault create --name MaxiPruebaTecKeyVault --resource-group ADO --location '$(location)'
      fi
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(acc)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ADO'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(vm_bicep)'      