trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Arroyo_Challenge-Test_Maximiliano'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name ADO --location 'East US'
      az keyvault create --name MaximilianoPruebaTecKeyVault --resource-group ADO --location 'East US'