
trigger:
- main

variables:
  location: 'East US'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Arroyo_Challenge-Test_Maximiliano'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name ADO --location '$(location)'
      az keyvault create --name MaxiPruebaTecKeyVault --resource-group ADO --location '$(location)'
      