trigger:
- none

variables:
  acc: 'Arroyo_Challenge-Test_Maximiliano'
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(acc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "ip"
      vm_name=$(az vm list --query "[0].name" -o tsv)
      echo $vm_name
      az vm show --resource-group ADO --name $vm_name --query publicIps --output tsv
    
