trigger:
- none

variables:
  acc: 'Arroyo_Challenge-Test_Maximiliano'
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(acc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "ip"
      az vm show --resource-group ADO --name ArroyoVM --query publicIps --output tsv
      az vm show --resource-group ADO --query publicIps --output tsv
