trigger: none

variables:
  location: 'East US'
  acc: 'Arroyo_Challenge-Test_Maximiliano'
  
pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    targetType: 'inline'
    azureSubscription: '$(acc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'    
    script: |
      echo "que"
      az vm list --query "[0].name" -o tsv
      $vmName = az vm list --query "[0].name" -o tsv
      # Install Chocolatey
      #az vm run-command invoke --resource-group ADO --name $(vmName) --command-id RunShellScript --scripts "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

      # Install Office using Chocolatey
      #choco install microsoft-office

