trigger: none

variables:
  location: 'East US'
  acc: 'Arroyo_Challenge-Test_Maximiliano'
  
pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    targetType: 'inline'
    azureSubscription: '$(acc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      vm_name=$(az vm list --query "[0].name" -o tsv)
      echo $vm_name
      echo "restarting"
      #az vm restart --resource-group ADO --name $vm_name
      # Install Chocolatey
      echo "Installing chocolatey"
      #az vm run-command invoke --resource-group ADO --name $vm_name --command-id RunPowerShellScript --scripts "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      echo "chocolately installed, reinitiating"
      az vm restart --resource-group ADO --name $vm_name
      echo "Installing office"
      az vm run-command invoke --resource-group ADO --name $vm_name --command-id RunPowerShellScript --scripts "choco install microsoft-office-deployment -y"
      echo "NodeJS"
      az vm run-command invoke --resource-group ADO --name $vm_name --command-id RunPowerShellScript --scripts "choco install nodejs -y"
  
