trigger: none

variables:
  location: 'East US'
  acc: 'Arroyo_Challenge-Test_Maximiliano'
  
pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    targetType: 'inline'
    azureSubscription: '$(acc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      vm_name=$(az vm list --query "[0].name" -o tsv)
      echo $vm_name
      # Install Chocolatey
      az vm run-command invoke --resource-group ADO --name $vm_name --command-id RunPowerShellScript --scripts "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
